name : Web Branding Diva
brand : Web Branding Diva
description : Web Branding Diva website
keyword : 
url : http://redsirendesign.github.io/webbrandingdiva.github.io/
email : masha@redsirendesign.com
twitter : redsirendesign
github : Red Siren Design
author : Red Siren Design
analytics : 
year : 2015
markdown : kramdown
exclude :
  - node_modules
