name : Foundation5/github pages/Jykill starter
brand : My Site
description : This is the description of my site
keyword : 
url : http://redsirendesign.github.io/webbrandingdiva.github.io/
email : daigo@daigofujiwara.com
twitter : DaigoFuji
github : DaigoFuji
author : Daigo Fujiwara
analytics : UA-8418273-8
year : 2015
markdown : kramdown
exclude :
  - node_modules
