name : /home
brand : atzorvas' corner
description : dead for now
keyword : tzorvas, atzorvas, jekyll, linux, ruby, python
url : http://tzorvas.com/
email : antonis@tzorvas.com
twitter : atzorvas
github : atzorvas
author : Antonis Tzorvas
analytics : UA-40901002-1
year : 2015
markdown : kramdown
