name : Foundation5/github pages/Jykill starter
brand : journey to the western software engineer
description : random musings longer than 140 characters but less than an ebook
keyword : 
url : http://dijonkitchen.github.io/
email : daigo@daigofujiwara.com
twitter : dijonkitchen
github : dijonkitchen
author : dijonkitchen
analytics : 
year : 2015
markdown : kramdown
